name: cli
permissions: write-all
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    tags:
      - "v*"
jobs:
  win-x86:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cmake -A win32 .
          cmake --build . --config MinSizeRel
        working-directory: cli
      - uses: actions/upload-artifact@v4
        with:
          name: identme.x86.exe
          path: cli/MinSizeRel/identme.exe
  win-x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cmake -A x64 .
          cmake --build . --config MinSizeRel
        working-directory: cli
      - uses: actions/upload-artifact@v4
        with:
          name: identme.x64.exe
          path: cli/MinSizeRel/identme.exe
  win-arm64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cmake -A ARM64 .
          cmake --build . --config MinSizeRel
        working-directory: cli
      - uses: actions/upload-artifact@v4
        with:
          name: identme.arm64.exe
          path: cli/MinSizeRel/identme.exe
  release:
    needs: [win-x86, win-x64, win-arm64]
    runs-on: ubuntu-latest
    steps:
      - id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v4
        with:
          name: identme.x86.exe
          path: .
      - uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: identme.exe
          asset_name: identme.x86.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v4
        with:
          name: identme.x64.exe
          path: .
      - uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: identme.exe
          asset_name: identme.x64.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v4
        with:
          name: identme.arm64.exe
          path: .
      - uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: identme.exe
          asset_name: identme.arm64.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
